# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: none # When active, APPLY_FIXES must also be defined as environment variable (in github/workflows/mega-linter.yml or other CI tool)

EXCLUDED_DIRECTORIES:
  - dougschveninger
  - common-tools
  - .git

PRINT_ALL_FILES: false

SHOW_ELAPSED_TIME: true
#EMAIL_REPORTER_EMAIL:
FILEIO_REPORTER: false
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: false
PRINT_ALPACA: false
